Añadiendo el controlador de recursos de la tabla tutorizados
2DAW-CarlosIII/instituto_21_22 pull request #31
Opened 2022-01-17 08:41 UTC by JoseAO

2022-01-18 11:01 UTC, JoseSanFulgencio commented on app/Http/Controllers/API/TutorizadoController.php
> +
Falta llamar el Resource: "TutorizadoResource"

2022-01-18 11:03 UTC, JoseSanFulgencio requested changes
Añadir el resource: "TutorizadoResource" al "TutorizadoController"

2022-01-18 11:10 UTC, albsierra requested changes
Es necesario corregir algunos errores.

2022-01-19 08:06 UTC, jamuga approved these changes

2022-01-19 08:07 UTC, jamuga approved these changes

2022-01-19 08:07 UTC, jamuga approved these changes

2022-01-19 08:08 UTC, merged