Controlador de recursos Grupos
2DAW-CarlosIII/instituto_21_22 pull request #36
Opened 2022-01-17 17:31 UTC by andres-jpg

Andrés Correa Sánchez

2022-01-18 10:27 UTC, JuanDavid102 commented on database/migrations/2022_01_17_080519_create_grupos_table.php
> +            $table->string('letra');
Por defecto el string (o varchar en la Base de Datos) por defecto da 255, pero la imagen propone que sea de 512. Habría que cambiarlo para que encajara con los requisitos

2022-01-18 10:31 UTC, JuanDavid102 commented on database/migrations/2022_01_17_080519_create_grupos_table.php
> +            $table->integer('curso');
Aunque técnicamente no es un error debido a las especificaciones, el maestro nos comentó que debido a que las id en realidad las genera por defecto de tipo bigint, sería recomendable que pusiéramos todas las variable, o al menos las que serán referenciadas, o vienen referidas de otras tablas como de tipo bigint

2022-01-18 10:35 UTC, JuanDavid102 commented on database/migrations/2022_01_17_080519_create_grupos_table.php
> +            $table->integer('curso');
Además, en la imagen podemos ver que tanto esta, curso, como letra, nombre, tutor y verificado están sin relleno, lo que significa que estas pueden ser nulas en algunos casos, siendo bueno, que las pongamos nulleables.

2022-01-18 10:36 UTC, JuanDavid102 commented on database/migrations/2022_01_17_080519_create_grupos_table.php
> +            $table->integer('curso');
También, aquellas que van a ser claves ajenas es necesario que además se ponga que es unsigned, para que encajen con la generación automática de la id.

2022-01-18 10:41 UTC, JuanDavid102 commented on routes/api.php
> +use APP\Http\Controllers\API\GrupoController;
A la hora de especificar la ruta, hay que tener en cuenta que el programa difiere entre minúsculas y mayúsculas. Siendo App la ruta correcta

2022-01-18 10:49 UTC, JuanDavid102 requested changes
Las rutas como tal funcionan bien. Realizando los cambios dichos en los comentarios estaría todo perfecto

2022-01-18 10:54 UTC, JuanDavid102 requested changes
Las rutas como tal funcionan correctamente, cuando se realicen los cambios puestos en los comentarios en teoría funcionaría todo perfectamente

2022-01-18 10:54 UTC, JuanDavid102 commented
Las rutas como tal funcionan correctamente, cuando se realicen los cambios puestos en los comentarios en teoría funcionaría todo perfectamente

2022-01-18 11:08 UTC, albsierra requested changes
Es necesario corregir algunos errores.

2022-01-19 08:25 UTC, andres-jpg commented on routes/api.php
> +use APP\Http\Controllers\API\GrupoController;
Todo corregido.

2022-01-19 08:37 UTC, JuanDavid102 approved these changes

2022-01-19 08:51 UTC, merged