Niveles brian
2DAW-CarlosIII/instituto_21_22 pull request #43
Opened 2022-01-18 09:14 UTC by BIANOX07

2022-01-18 10:51 UTC, baLdr-edu commented on app/Http/Controllers/API/FaltaProfesorController.php
> +<?php
Este controlador no se utiliza

2022-01-18 10:52 UTC, baLdr-edu commented on app/Http/Controllers/API/FaltaProfesorController.php
> +class FaltaProfesorController extends Controller
Este controlador no se utiliza

2022-01-18 11:10 UTC, albsierra requested changes
Es necesario corregir algunos errores.

2022-01-21 07:18 UTC, albsierra approved these changes

2022-01-21 07:18 UTC, merged